apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: cavproxy
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: cavproxy
  template:
    metadata:
      labels:
        app: cavproxy
    spec:
      containers:
        - name: cavproxy
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: proxy
              containerPort: {{ .Values.port }}

          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | quote }}
              memory: {{ .Values.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.resources.limits.cpu | quote }}
              memory: {{ .Values.resources.limits.memory | quote }}

          env:
            - name: NDHOME
              value: {{ .Values.ndhome | quote }}
            - name: LD_LIBRARY_PATH
              value: {{ .Values.ldLibraryPath | quote }}
            - name: CAV_APP_AGENT_NDCHOST
              value: {{ .Values.ndcHost | quote }}
            - name: CAV_APP_AGENT_NDCPORT
              value: {{ .Values.ndcPort | quote }}
            - name: CAV_APP_AGENT_NDC_COMM_PROTOCOL
              value: {{ .Values.ndcCommProtocol | quote }}
            - name: CAV_APP_AGENT_PROXYPORT
              value: {{ .Values.port | quote }}
            - name: CAV_APP_AGENT_AGENTLOGGINGMODE
              value: {{ .Values.loggingMode | quote }}
            - name: CAV_APP_AGENT_VERIFY_SERVER_CERT
              value: {{ .Values.verifyServerCert | quote }}
            - name: CAV_APP_AGENT_VERIFY_HOST_NAME
              value: {{ .Values.verifyHostName | quote }}
            - name: CAV_APP_AGENT_ACCEPT_SELF_SIGNED_CERT
              value: {{ .Values.acceptSelfSignedCert | quote }}
            - name: CAV_APP_AGENT_ACCEPT_EXPIRED_CERT
              value: {{ .Values.acceptExpiredCert | quote }}
            - name: CAV_APP_AGENT_ACCEPT_REVOKED_CERT
              value: {{ .Values.acceptRevokedCert | quote }}
            - name: CAV_APP_AGENT_SERVER_CA_CERT
              value: {{ .Values.serverCaCert | quote }}
            - name: CAV_APP_AGENT_CLIENT_CERT
              value: {{ .Values.clientCert | quote }}
            - name: CAV_APP_AGENT_CLIENT_KEY
              value: {{ .Values.clientKey | quote }}

          volumeMounts:
            - name: proxy-config
              mountPath: {{ .Values.ndhome }}/proxy/config

      volumes:
        - name: proxy-config
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: cavproxy
  namespace: {{ .Values.global.namespace }}
spec:
  type: ClusterIP
  selector:
    app: cavproxy
  ports:
    - name: proxy
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.port }}
