apiVersion: v1
kind: ConfigMap
metadata:
  name: webhook-injector-config
  namespace: {{ .Release.Namespace }}
data:
  {{- if .Values.NDController }}
  controller: | {{ printf "\n" }}
    {{- toYaml .Values.NDController | indent 4 }}
  {{- end }}
  {{- if .Values.NDController }}
  flexMatch: "{{ .Values.flexMatch }}"
  {{- end }}
  instrumentation: | {{ printf "\n" }}
    {{- toYaml .Values.instrumentationRules | indent 4 }}
  injectionTemplates: | {{ printf "\n" }}
    {{- toYaml .Values.instrumentationTemplates | indent 4 }}
