#Service Account
kind: ServiceAccount
apiVersion: v1
metadata:
  name: cmon-service-account
  namespace: {{ .Release.Namespace }}
---
#Cmon Role
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cmon-role
rules:
- apiGroups:
    - apps
  resources:
    - deployments
    - replicasets
    - replicationcontrollers
    - daemonsets
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - metrics.k8s.io
  resources:
    - pods
    - nodes
  verbs:
    - get
    - list
    - watch
- apiGroups:
  - ""
  resources:
  - services
  - events
  - endpoints
  - pods
  - nodes
  - persistentvolumeclaims
  - replicationcontrollers
  - limitranges
  - nodes/proxy
  - nodes/metrics
  - nodes/spec
  - nodes/stats
  - componentstatuses
  - resourcequotas
  - count/persistentvolumeclaims
  - count/services
  - count/secrets
  - count/configmaps
  - count/replicationcontrollers
  - count/deployments.apps
  - count/replicasets.apps
  - count/statefulsets.apps
  - count/jobs.batch
  - count/cronjobs.batch
  - count/deployments.extensions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - get
  - list
  - watch
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - "autoscaling"
  resources:
  - horizontalpodautoscalers
  verbs:
  - list
  - watch
- apiGroups:  # To create the leader election token
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - update
- nonResourceURLs:
  - "/version"
  - "/healthz"
  - "/metrics"
  verbs:
  - get
---
#ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cmon-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cmon-role
subjects:
- kind: ServiceAccount
  name: cmon-service-account
  namespace: {{ .Release.Namespace }}
---
#DaemonSet
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cmon
  namespace: {{ .Release.Namespace }}
  labels:
    name: cmon
    app: cmon
spec:
  selector:
    matchLabels:
      name: cmon
  template:
    metadata:
      labels:
        name: cmon
        app: cmon
    spec:
      hostPID: true
      serviceAccountName: cmon-service-account
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
      containers:
        - name: cmon
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
               name: cmon-config
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          ports:
          - containerPort: {{ .Values.port }}
            hostPort: {{ .Values.port }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu | quote }}
              memory: {{ .Values.resources.limits.memory | quote }}
            requests:
              cpu: {{ .Values.resources.requests.cpu | quote }}
              memory: {{ .Values.resources.requests.memory | quote }}
          volumeMounts:
          - name: varlogs
            mountPath: /var/log
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true
          - name: hostsys
            mountPath: /host/sys
          - name: hostproc
            mountPath: /host/proc
          - name: varrun
            mountPath: /var/run
          - name: cmon-volume
            mountPath: /home/cavisson/monitors/sys/cmon.env
            subPath: cmon.env
          - name: nf-volume
            mountPath: /home/cavisson/monitors/sys/nf.env
            subPath: nf.env
        #  - name: tls-volume
         #   mountPath: /home/cavisson/monitors/certs/
            readOnly: true
      volumes:
      - name: varlogs
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: hostsys
        hostPath:
          path: /sys
      - name: hostproc
        hostPath:
          path: /proc
      - name: varrun
        hostPath:
          path: /var/run
      - name: cmon-volume
        configMap:
          name: cmon-config
          defaultMode: 440
      - name: nf-volume
        configMap:
          name: cmon-config
          defaultMode: 440
      #- name: tls-volume
      #  secret:
      #   secretName: {{ .Values.tlsSecretName }}
